# Generated by Django 4.0.5 on 2022-06-27 18:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="placeId",
            field=models.UUIDField(
                default=uuid.UUID("ab990506-380a-4cea-8eda-d9ce7a7f57a2")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reviewId",
            field=models.UUIDField(
                default=uuid.UUID("c9a09696-c8b1-40da-804c-1a6a3adfb1e4")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="userId",
            field=models.UUIDField(
                default=uuid.UUID("98faa5fe-c794-4298-9171-7cf26107d50b")
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6048282f-70a6-45fe-9aae-0be4e5192f2d"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="placehistory",
            name="place_id",
            field=models.UUIDField(
                default=uuid.UUID("7507379f-119b-4b52-9d07-f28b5c957578")
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("4e47ae00-635b-4f7b-97fb-ce1601c6dc1b")
            ),
        ),
        migrations.AlterField(
            model_name="pointhistory",
            name="review_id",
            field=models.UUIDField(
                default=uuid.UUID("00ee4457-1d60-4992-9797-63d7fd72c7f2")
            ),
        ),
    ]
