# Generated by Django 4.0.5 on 2022-06-23 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mileage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="placeId",
            new_name="place_id",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="userId",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="point",
            name="id",
        ),
        migrations.AlterField(
            model_name="point",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
