# Generated by Django 4.0.5 on 2022-06-27 19:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0002_alter_event_action_alter_event_placeid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="placeId",
            field=models.UUIDField(
                default=uuid.UUID("682a489d-822b-4840-9d93-6772db4ed820")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reviewId",
            field=models.UUIDField(
                default=uuid.UUID("0f4ec316-c64e-479d-a30f-b89fb08b2fd7")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="userId",
            field=models.UUIDField(
                default=uuid.UUID("f46f319c-bc37-408d-95a7-1d0020e2356b")
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1092d6e2-2cd0-470b-9a53-23212a32709c"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="placehistory",
            name="place_id",
            field=models.UUIDField(
                default=uuid.UUID("be1cf563-58a0-48ac-bfb5-11dbcf12f57e")
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("a26b6914-b644-45f0-9df9-f3b84662cfcb")
            ),
        ),
        migrations.AlterField(
            model_name="pointhistory",
            name="review_id",
            field=models.ForeignKey(
                db_column="review_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mileage.review",
            ),
        ),
    ]
