# Generated by Django 4.0.5 on 2022-06-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mileage', '0002_rename_placeid_review_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placehistory',
            name='place_id',
            field=models.OneToOneField(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='mileage.place'),
        ),
        migrations.AlterField(
            model_name='point',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='place_id',
            field=models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, to='mileage.place'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review_id',
            field=models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='mileage.review'),
        ),
    ]
