# Generated by Django 4.0.5 on 2022-06-27 20:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0003_alter_event_placeid_alter_event_reviewid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placehistory",
            name="id",
        ),
        migrations.AlterField(
            model_name="event",
            name="placeId",
            field=models.UUIDField(
                default=uuid.UUID("393238c0-6992-41a3-ac07-926c40a5cb79")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reviewId",
            field=models.UUIDField(
                default=uuid.UUID("449faaf8-1b32-4336-a449-50a9e9aecf86")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="userId",
            field=models.UUIDField(
                default=uuid.UUID("cfb3a43c-06d2-4955-b689-a39e2afccead")
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("128d13af-f669-4a15-92e4-16abf195e89c"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="placehistory",
            name="place_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="mileage.point",
                verbose_name="place_id",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("d10a2f73-1ccd-4abe-859b-85306c873b89")
            ),
        ),
    ]
