# Generated by Django 4.0.5 on 2022-06-27 20:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mileage", "0004_remove_placehistory_id_alter_event_placeid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="placeId",
            field=models.UUIDField(
                default=uuid.UUID("67cb907e-71f4-4303-acff-6f612f507597")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reviewId",
            field=models.UUIDField(
                default=uuid.UUID("a884e14b-7968-4dce-8886-d746220ed447")
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="userId",
            field=models.UUIDField(
                default=uuid.UUID("2f2e3345-5bf1-4ef6-88ad-a30225e83de4")
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7cc4d3ec-6a59-46c5-a47a-bf7e25ff08ef"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="placehistory",
            name="place_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="mileage.place",
                verbose_name="place_id",
            ),
        ),
        migrations.AlterField(
            model_name="point",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("b8bc7280-72c3-417b-bd63-7d935cbc1b80")
            ),
        ),
    ]
